(when (eq system-type 'darwin) ;; mac specific settings
  (setq mac-control-modifier 'control)
  (setq mac-option-modifier 'meta)
  (setq mac-command-modifier 'super)
  (global-set-key (kbd "s-s")
                  'save-buffer)
  (global-set-key (kbd "s-k")
                  'kill-this-buffer)
  (global-set-key (kbd "s-c")
                  'kill-ring-save)
  (global-set-key (kbd "s-x")
                  'kill-region)
  (global-set-key (kbd "s-v")
                  'yank)
  (global-set-key (kbd "s-=")
                  'text-scale-increase)
  (global-set-key (kbd "s--")
                  'text-scale-decrease)
  (global-set-key (kbd "s-z")
                  'undo-only)
  (global-set-key (kbd "s-b")
                  'switch-to-buffer)
  (global-set-key (kbd "s-/")
                  'hippie-expand)
  (global-set-key (kbd "s-a")
                  'mark-whole-buffer)
  (global-set-key [s-down]
                  'duplicate-current-line-or-region)
  (global-set-key (kbd "<s-right>")
                  'next-buffer)
  (global-set-key (kbd "<s-left>")
                  'previous-buffer)

  ;; window-splitting
  (global-set-key (kbd "s-1")
                  'delete-other-windows)
  (global-set-key (kbd "s-2")
                  'split-window-vertically)
  (global-set-key (kbd "s-3")
                  'split-window-horizontally)
  (global-set-key (kbd "s-4")
                  'delete-other-windows-vertically)
  (global-set-key (kbd "TAB")
                  'company-complete-common)
  )

(global-set-key (kbd "C-a") 'smart-beginning-of-line)
